.\"
.\"	@file wmc2d.1		@brief coretemp/cpufreq monitor dockapp
.\"
.\"	Copyright (c) 2004, 2009 - 2012 by Lutz Sammer.  All Rights Reserved.
.\"
.\"	Contributor(s):
.\"
.\"	License: AGPLv3
.\"
.\"	This program is free software: you can redistribute it and/or modify
.\"	it under the terms of the GNU Affero General Public License as
.\"	published by the Free Software Foundation, either version 3 of the
.\"	License.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU Affero General Public License for more details.
.\"
.\"	$Id$
.\" ------------------------------------------------------------------------
.TH "wmc2d" 1 "2012-06-11" "1" "wmc2d Manual"

.SH NAME
wmc2d \- a coretemp/cpufreq monitor dockapp

.SH SYNOPSIS
.B wmc2d
.BI [\-?|\-h]
.BI [\-3jJsw]
.BI [\-0 \ zone-name ]
.BI [\-1 \ zone-name ]
.BI [\-c \ first ]
.BI [\-n \ cpus ]
.BI [\-r \ rate ]
.BI [\-t \ freq ]
.BI [\-z \ zones ]

.SH DESCRIPTION
This is a small dockapp, which shows the core temperature and CPU frequency
from 2 upto 4 cores/CPUs and the temperature of upto two thermal zones, which
are normaly the motherboard temperature.
.PP
All cpus, which are supported by the linux kernel "coretemp" and "cpufreq"
modules, could be monitored.  f.e. core 2, atom and core iX.
.PP
All thermal zones which could be read from files are supported.  f.e.  ACPI
through /sys/class/thermal/thermal_zoneX/temp or hardware sensors through
/sys/devices/platform/<chip>/tempX_input.

.SH OPTIONS
.TP
.B \-?|\-h
Show short usage help and exit.  The help is printed to stdout.  A note to all
developers: please print to stdout!
.TP
.BI \-0 \ zone-name
File name of the thermal zone 0, defaults to ACPI thermal zone 0
(/sys/class/thermal/thermal_zone0/temp).
.TP
.BI \-1 \ zone-name
File name of the thermal zone 1, defaults to ACPI thermal zone 1
(/sys/class/thermal/thermal_zone1/temp).
.TP
.BI \-c \ first
Number of the first CPU to use in this dockapp, can be used to monitor more
than 4 core or cpus, with multiple dockapps.
.TP
.B \-j
Join two CPUs, the frequency information of two cores is alternative displayed.
(Useful for hyper-threading CPUs)
.TP
.B \-J
Join two CPUs, only the temperature information of every second core is
displayed. (Useful for hyper-threading CPUs) (Since kernel 2.6.35 there is
only a sensor for physical cores)
.TP
.B \-3
Handle linux 3.x coretemp.  (Since kernel 3.0 the path and filenames are
changed)
.TP
.BI \-n \ cpus
Number of CPUs to display.  Currently only 2 or 4 CPUs are supported,  if you
need others, please make a feature request or send a patch.
.TP
.BI \-r \ rate
Refresh rate of the temperature and frequency informations in milliseconds,
defaults to 1500ms.  Shorter means more CPU usage and more updates.
.TP
.B \-s
Sleep while screen-saver is running or video is blanked.  The dockapp sleeps
and did't use any CPU cyles, while the display is switched off.  Saves energy
on laptops.
.TP
.BI \-t \ freq
Turbo boost frequency in Mhz (f.e. 1734000 for 1.73 Ghz), when the turbo
boost frequency is reached, the frequency is shown in red.
.TP
.B \-w
Start in window mode, used for debugging.  The dockapp gets the normal window
borders and title.
.TP
.BI \-z \ zones
Number of thermal zones to display.  Currently only 0, 1 or 2 are
supported.  Thermal zone 0 is normaly the motherboard temperature.

.SH FILES
.TP
.I /sys/devices/platform/coretemp.X/temp1_input
kernel cpu temperature information
.TP
.I /sys/devices/system/cpu/cpuX/cpufreq/scaling_cur_freq
kernel cpu frequency information
.TP
.I /sys/class/thermal/thermal_zoneX/temp
kernel ACPI thermal zones
.TP
.I /sys/devices/platform/<sensor>/tempX_input
kernel thermal hardware sensor

.SH AUTHOR
Copyright (C) 2004, 2009, 2010 Lutz Sammer.  License: AGPLv3.
